DATA:
  TRAIN_FILE : 'dataset/few_nerd/train_S0.json'
  VAL_FILE : 'dataset/few_nerd/dev_S0.json'
  TEST_FILE : 'dataset/few_nerd/test.json'
  SAVE_DIR : 'results_nospec'

MODEL:
  PLM_NAME : 'roberta-base'
  MASK_TOKEN : '<mask>'
  ADAPTERS : False
  SEED: 11

TRAIN:
  BATCH_SIZE : 8
  LR : 1e-3
  LAMBD : 1e-7
  WD : 15
  EPOCHS : 30
  SEED : 11
  N_MASK : 1